JobStationUI/Controllers/JobOfferController.cs
using AutoMapper;

using JobStation.Dto;
using JobStation.Model;
using JobStation.Utility;
using JobStationUI.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace JobStationUI.Controllers
{
    public class JobOfferController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        public JobOfferController(IUnitOfWork unitOfWork,
            IMapper mapper)
        {
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var jobOffer = new List<JobOfferDto>();
            var response = await unitOfWork.JobOfferService.Get();
            if (response != null && response.StatusCode == HttpStatusCode.OK && response.Data.Data != null)
                jobOffer = response.Data.Data;
            return View(jobOffer);
        }
        [HttpGet]
        public async Task<IActionResult> Manage([FromQuery] string guid)
        {
            var model = new JobOfferModel() { };
            var jobOfferResponse = await unitOfWork.JobOfferService.GetByGuid(guid);
            if (jobOfferResponse != null && jobOfferResponse.StatusCode == HttpStatusCode.OK && jobOfferResponse.Data.Data != null)
                model = mapper.Map<JobOfferModel>(jobOfferResponse.Data.Data);

            await SelectListData(model);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(JobOfferModel model)
        {
            await SelectListData(model);
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Fill required fields!");
                return View(model);
            }

            IRestResponse<Response<JobOfferDto>> JobOfferResponse;
            var message = "";
            var jobOfferDetails = await unitOfWork.JobOfferService.GetByGuid(model.UniqueGuid);
            if (jobOfferDetails != null && jobOfferDetails.StatusCode == HttpStatusCode.OK && jobOfferDetails.Data.Data != null)
                JobOfferResponse = await unitOfWork.JobOfferService.Update(jobOfferDetails.Data.Data.Id, model);
            else
                JobOfferResponse = await unitOfWork.JobOfferService.Add(model);

            if (JobOfferResponse != null && (JobOfferResponse.StatusCode == HttpStatusCode.Created ||
                JobOfferResponse.StatusCode == HttpStatusCode.OK) && JobOfferResponse.Data.Data != null)
            {
                message = "Record saved successfully.";
                TempData["type"] = "success";
                return Json(new { success = true, msg = @message });
            }

            return Json(new { success = false, msg = "Some error occured" });
        }

       
        private async Task SelectListData(JobOfferModel model)
        {
            model.CategoryItems = new List<SelectListItem>() { new SelectListItem("Select Category", "") };
            var categoryResponse = await unitOfWork.CategoryService.Get();
            if (categoryResponse != null && categoryResponse.StatusCode == HttpStatusCode.OK && categoryResponse.Data.Data != null)
                model.CategoryItems.AddRange(categoryResponse.Data.Data.Select(e => new SelectListItem() { Text = e.CategoryName, Value = e.Id.ToString() }).ToList());

            model.JobTypeItems = new List<SelectListItem>() { new SelectListItem("Select Job type", "") };
            var JobTypeResponse = await unitOfWork.JobTypeService.Get();
            if (JobTypeResponse != null && JobTypeResponse.StatusCode == HttpStatusCode.OK && JobTypeResponse.Data.Data != null)
                model.JobTypeItems.AddRange(JobTypeResponse.Data.Data
                    .Select(e => new SelectListItem() { Text = e.TypeName, Value = e.Id.ToString() }).ToList());

            model.CompanyItems = new List<SelectListItem>() { new SelectListItem("Select Organisation", "") };
            var companyResponse = await unitOfWork.OrganisationDetailService.Get();
            if (companyResponse != null && companyResponse.StatusCode == HttpStatusCode.OK && companyResponse.Data.Data != null)
                model.CompanyItems.AddRange(companyResponse.Data.Data.Select(e => new SelectListItem() { Text = e.OrganisationName, Value = e.Id.ToString() }).ToList());

            model.LocationItems = new List<SelectListItem>() { new SelectListItem("Select Location", "") };
            var jobLocationResponse = await unitOfWork.JobLocationService.Get();
            if (jobLocationResponse != null && jobLocationResponse.StatusCode == HttpStatusCode.OK && jobLocationResponse.Data.Data != null)
                model.LocationItems.AddRange(jobLocationResponse.Data.Data
                    .Select(e => new SelectListItem() { Text = e.City, Value = e.Id.ToString() }).ToList());
        }
    }
}

JobStationUI/Views/JobOffer/Index.cshtml
@model List<JobOfferDto>
@inject IClaimsService claimsService
@inject IUnitOfWork unitOfWork
@{
    ViewBag.Title = "Job Offers";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

    //var categories = (List<BlogCategoryDto>)ViewBag.Categories;
    //var pageUrl = $"/BlogPost?count={Model.Params.RecordPerPage}&categoryId={Model.Params.CategoryId}&q={Model.Params.Q}&status={Model.Params.Status}&countrycode={Model.Params.CountryCode}&StateCode={Model.Params.StateCode}&city={Model.Params.City}";
}

<div class="dashboard_main">

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="dashboard_main_heading">
                    <div class="heading_left">
                        <h2>Job Offer</h2>
                    </div>
                    <div class="heading_right">
                        <a asp-area="" asp-controller="JobOffer" asp-action="Manage" class="btn-main">
                            <i class="fal fa-plus-circle"></i> Add New Job Offer
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="dashboard_main_body">
        <div class="container-fluid">
            <div class="row">
                <partial name="~/Views/Shared/_ErrorMessage.cshtml" />
                <div class="col-md-12">
                    <div class="table_main">
                        <table class="table table_style table-hover" id="organisation-table">
                            <thead class="cf">
                                <tr>
                                    <th>Id</th>
                                    <th>Title</th>
                                    <th>Experience</th>
                                    <th>Salary</th>
                                    <th>Added On</th>
                                    <th>Last Updated On</th>
                                    <th class="no-sort">Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                @if (Model != null)
                                {

                                    foreach (var offer in Model)
                                    {
                                <tr>

                                    <td>@offer.Id</td>
                                    <td>@offer.Title</td>
                                    <td>@offer.Experience</td>
                                    <td>@offer.Salary</td>  
                                    <td data-sort='@offer.CreatedOn.ToString("yyyyMMdd")'>@offer.CreatedOn.ConvertToUserTime(unitOfWork.ClaimsService.GetTimeZone()).ToString("dd MMM, yyyy  |  hh:mm tt")</td>
                                    <td data-sort='@offer.UpdatedOn.ToString("yyyyMMdd")'>@offer.UpdatedOn.ConvertToUserTime(unitOfWork.ClaimsService.GetTimeZone()).ToString("dd MMM, yyyy  |  hh:mm tt")</td>
                                    <td>
                                        <a class="btn icon_btn" asp-area="" asp-controller="JobOffer" asp-action="Manage" asp-route-guid="@offer.UniqueGuid"
                                           data-bs-toggle="tooltip" data-bs-placement="top" title="Edit">
                                            <i class="fal fa-edit"></i>
                                        </a>


                                        <a class="btn btn-sm btn-danger delete-offer" href="#" data-href="/JobOffer/Delete/@offer.Id"
                                           data-bs-toggle="tooltip" data-bs-placement="top" title="Delete"
                                           data-bs-original-title="Delete" aria-label="Delete">
                                            <i class="fal fa-trash"></i>
                                        </a>

                                    </td>
                                </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).on('click', '.delete-offer', function (e) {
            e.preventDefault();
            var _self = $(this);
            bootbox.confirm({
                title: "Confirm?",
                message: "Are you sure for this action?",
                centerVertical: false,
                buttons: {
                    cancel: {
                        label: '<i class="fa fa-times"></i> Cancel',
                        className: 'btn-danger'
                    },
                    confirm: {
                        label: '<i class="fa fa-check"></i> Confirm',
                        className: 'btn-success'
                    }
                },
                callback: function (result) {
                    if (result) {
                        $.ajax({
                            type: "POST",
                            url: _self.attr('data-href'),
                            success: function (data) {
                                if (data.success) {

                                    toastr.success(data.msg);

                                    setTimeout(function () {
                                        window.location.reload();
                                    }, 2000);

                                } else {
                                    $('.ajax-loader').addClass('d-none');
                                    toastr.error(data.msg);
                                }

                            },
                            error: function (req, error) {
                                toastr.error(req.responseText);
                                $('.ajax-loader').addClass('d-none');
                            },
                            beforeSend: function (data) {
                                $('.ajax-loader').removeClass('d-none');
                            }
                        });

                    }
                }
            });
        });
    </script>

}




@*<div class="dashboard_main_body">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <div class="table_main">
                        <table class="table table_style table-hover" id="blog-post-table">

                            <thead class="cf">
                                <tr>

                                    <th>Title @Html.Raw(SortingHtml.GetSortingHtml(pageUrl, "title", Model.Params.SortBy, Model.Params.SortDirection))</th>
                                    <th> @Html.Raw(SortingHtml.GetSortingHtml(pageUrl, "category", Model.Params.SortBy, Model.Params.SortDirection))</th>
                                    <th>Author @Html.Raw(SortingHtml.GetSortingHtml(pageUrl, "author", Model.Params.SortBy, Model.Params.SortDirection))</th>
                                    <th class="text-center">Sticky Post @Html.Raw(SortingHtml.GetSortingHtml(pageUrl, "stickypost", Model.Params.SortBy, Model.Params.SortDirection))</th>
                                    <th>Post Date @Html.Raw(SortingHtml.GetSortingHtml(pageUrl, "postdate", Model.Params.SortBy, Model.Params.SortDirection))</th>
                                    <th class="text-center">Status @Html.Raw(SortingHtml.GetSortingHtml(pageUrl, "status", Model.Params.SortBy, Model.Params.SortDirection))</th>
                                    <th class="no-sort text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Data != null && Model.Data.Count > 0)
                                {
                                    foreach (var m in Model.Data)
                                    {
                                        <tr>
                                            <td>
                                                @m.Title
                                                <br />
                                                <small>
                                                    <em>
                                                        <a href="/blog/@m.Slug" target="_blank">@m.Slug</a>
                                                    </em>
                                                </small>
                                            </td>
                                            <td>@m.</td>
                                            <td>@m.AuthorName</td>
                                            <td class="text-center">@m.StickyPost</td>
                                            <td data-sort='@m.PostDate.ToString("yyyyMMdd")'>@m.PostDate.ConvertToUserTime(unitOfWork.ClaimsService.GetTimeZone()).ToString("dd MMM, yyyy  |  hh:mm tt")</td>
                                            <td class="text-center">
                                                @if (@m.Status.ToLower() == "published")
                                                {
                                                    <span class="active-status">@m.Status</span>
                                                }
                                                else
                                                {
                                                    <span class="in-active-status">@m.Status</span>
                                                }
                                            </td>


                                            <td class="text-center">
                                                <span class="toggle_span" data-id="sub_menu_@{@m.UniqueGuid}">
                                                    <a class="icon_btn" data-bs-toggle="tooltip" data-bs-placement="right" title="Action"><i class="fa-light fa-circle-location-arrow"></i></a>
                                                    <div class="collapse mapping_list_collapse" id="sub_menu_@{@m.UniqueGuid}" data-id="sub_menu_@{@m.UniqueGuid}">
                                                        <ul>
                                                            <li>
                                                                <a class="update-blog-post" asp-area="" asp-controller="BlogPost" asp-action="Manage" asp-route-guid="@m.UniqueGuid">
                                                                    Edit
                                                                </a>
                                                            </li>

                                                            <li>
                                                                <a class="preview-blog-post" asp-area="" asp-controller="BlogPost" asp-action="PreviewBlogPost" asp-route-guid="@m.UniqueGuid" target="_blank">
                                                                    Preview Blog Post
                                                                </a>
                                                            </li>
                                                            @if (User.IsInRole("SuperAdmin"))
                                                            {
                                                                <li>
                                                                    <a href="#" class="delete-post" data-id="@m.Id" data-guid="@m.UniqueGuid">
                                                                        Delete
                                                                    </a>
                                                                </li>

                                                            }


                                                        </ul>
                                                    </div>
                                                </span>
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="7" class="text-center">
                                            <img src="~/themes/back-end/images/no_result.gif" class="no-result" />
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


        </div>
    </div>*@

JobStationUI/Views/JobOffer/Manage.cshtml
@model JobOfferModel
@inject IUnitOfWork unitOfWork
@{
    ViewBag.Title = "Job Offers";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}



<div class="dashboard_main">

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-12">
                <div class="dashboard_main_heading">
                    <div class="heading_left">
                        @if (Model.Id > 0)
                        {
                            <h2>Update <em>@Model.Title</em> Job Offer</h2>
                        }
                        else
                        {
                            <h2>Add New Job Offer</h2>
                        }
                    </div>
                    <div class="heading_right">
                        <a class="btn-main" asp-area="" asp-controller="JobOffer" asp-action="Index">
                            <i class="fa fa-arrow-circle-left"></i> Back to Post List
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="dashboard_main_body">
        <partial name="~/Views/Shared/_ErrorMessage.cshtml" />
        <form asp-controller="JobOffer" asp-action="Manage" method="post" id="JobOfferForm" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UniqueGuid" />
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="website_settings">


                            <div class="row">
                                <div class="col-md-6" style="border: solid 1px #4897d5; padding: 10px; border-right: none !important;">
                                    <div class="row">

                                        <div class="col-sm-12">

                                            <fieldset>
                                                <legend>Basic Details</legend>

                                                <div class="row">

                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>Title*</label>
                                                            <input type="text" asp-for="Title" class="form-control" placeholder="Title*" />
                                                            <span asp-validation-for="@Model.Title" class="text-danger"></span>
                                                        </div>
                                                    </div>

                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label>Description</label>
                                                            <textarea class="form-control" asp-for="Description"></textarea>
                                                            <span asp-validation-for="@Model.Description" class="text-danger"></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </fieldset>


                                            <div class="col-md-12">
                                                <fieldset class="scheduler-border">
                                                    <legend>Category & JobType</legend>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="form-group">
                                                                <label>Category*</label>
                                                                <select class="form-control form-select" asp-for="JobCategoryId" asp-items="Model.CategoryItems">
                                                                </select>
                                                                <span asp-validation-for="JobCategoryId" class="text-danger"></span>
                                                            </div>
                                                        </div>

                                                        <div class="col-md-12">
                                                            <div class="form-group">
                                                                <label>Job Type*</label>
                                                                <select class="form-control form-select" asp-for="JobTypeId" asp-items="Model.JobTypeItems">
                                                                </select>
                                                                <span asp-validation-for="JobTypeId" class="text-danger"></span>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </fieldset>
                                            </div>


                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6" style="border: solid 1px #4897d5; padding: 10px; border-right: none !important;">
                                    <div class="col-md-12">
                                        <fieldset class="scheduler-border">
                                            <legend class="scheduler-border">IsActive</legend>
                                            <div class="control-group">
                                                <label class="switch" for="IsActive">
                                                    <input type="checkbox" asp-for="IsActive">
                                                    <span asp-validation-for="IsActive" class="slider round text-danger"></span>
                                                </label>
                                            </div>
                                        </fieldset>
                                    </div>

                                    <div class="col-md-12">
                                        <fieldset class="scheduler-border">
                                            <legend>Company & Location</legend>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>Company*</label>
                                                        <select class="form-control form-select" asp-for="CompanyId" asp-items="Model.CompanyItems">
                                                            <option value="">Select Company</option>
                                                        </select>
                                                        <span asp-validation-for="CompanyId" class="text-danger"></span>
                                                    </div>
                                                </div>

                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>Location*</label>
                                                        <select class="form-control form-select" asp-for="LocationId" asp-items="Model.LocationItems">
                                                        </select>
                                                        <span asp-validation-for="LocationId" class="text-danger"></span>
                                                    </div>
                                                </div>

                                            </div>
                                        </fieldset>
                                    </div>


                                    <div class="col-md-12">
                                        <fieldset class="scheduler-border">
                                            <legend>Experience & Salary</legend>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>Title*</label>
                                                        <input type="text" asp-for="Experience" class="form-control" placeholder="Experience*" />
                                                        <span asp-validation-for="@Model.Experience" class="text-danger"></span>
                                                    </div>
                                                </div>

                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>Title*</label>
                                                        <input type="text" asp-for="Salary" class="form-control" placeholder="Salary*" />
                                                        <span asp-validation-for="@Model.Salary" class="text-danger"></span>
                                                    </div>
                                                </div>

                                            </div>
                                        </fieldset>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="sticky-button-section">
                <div class="form-group text-center">                   
                    <input type="submit" class="btn-main" name="Action" value="Save" />
                </div>
            </div>
        </form>
    </div>
</div>

@section scripts{

    <partial name="~/Views/Shared/_TinymceScripts.cshtml" />
    <partial name="~/Views/Shared/_GijgoDatePicker.cshtml" />
    <partial name="~/Views/Shared/_ChosenSelect.cshtml" />
    <script>
        $(function () {
            tinymceInit('#Description');


            $('#PostDate').datepicker({
                uiLibrary: 'bootstrap5',
                format: 'mm/dd/yyyy'
            });
        });
    </script>
}