JobStationUI/Controllers/OrganisationDetailsController.cs
using AutoMapper;
using JobStation.Dto;
using JobStation.Model;
using JobStation.Utility;
using JobStationUI.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace JobStationUI.Controllers
{
    public class OrganisationDetailsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        public OrganisationDetailsController(IUnitOfWork unitOfWork,
            IMapper mapper)
        {
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index([FromQuery] string q= "")
        {
            var OrganisationDetails = new List<OrganisationDetailsDto>();
            var response = await unitOfWork.OrganisationDetailService.Get(q);

            if (response != null && response.StatusCode == System.Net.HttpStatusCode.OK && response.Data.Data != null)
                OrganisationDetails = response.Data.Data;

            return View(OrganisationDetails);
        }

        [HttpGet]
        public async Task<IActionResult> Manage([FromQuery] string guid)
        {
            var model = new OrganisationDetailsModel()
            {
            };
            var organisationDetailsResponse = await unitOfWork.OrganisationDetailService.GetByGuid(guid);
            if (organisationDetailsResponse != null && organisationDetailsResponse.StatusCode == HttpStatusCode.OK && organisationDetailsResponse.Data.Data != null)
            {
                 model = mapper.Map<OrganisationDetailsModel>(organisationDetailsResponse.Data.Data);
                
            }
            
            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> Manage(OrganisationDetailsModel model)
        {
            if(!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Fill required fields!");
                return View(model);
            }

            IRestResponse<Response<OrganisationDetailsDto>> OrganisationDetailsResponse;
            var message = "";
            var organisationDetails = await unitOfWork.OrganisationDetailService.GetByGuid(model.UniqueGuid);
            if (organisationDetails != null && organisationDetails.StatusCode == HttpStatusCode.OK && organisationDetails.Data.Data != null)
                OrganisationDetailsResponse = await unitOfWork.OrganisationDetailService.Update(model.Id, model);
            else
                OrganisationDetailsResponse = await unitOfWork.OrganisationDetailService.Add(model);

            if (OrganisationDetailsResponse != null && (OrganisationDetailsResponse.StatusCode == HttpStatusCode.Created || 
                OrganisationDetailsResponse.StatusCode == HttpStatusCode.OK) && OrganisationDetailsResponse.Data.Data != null)
            {
                //TempData["type"] = "success";
                //TempData["message"] = "Record saved successfully";

                //return RedirectToAction("Index", "OrganisationDetails");
                message = "Record saved successfully.";
                TempData["type"] = "success";
                return Json(new { success = true, msg = @message });
            }
          
            return Json(new { success = false, msg = "Some error occured" });
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var organisation = await unitOfWork.OrganisationDetailService.GetById(id);
            if (organisation == null || organisation.StatusCode != HttpStatusCode.OK || organisation.Data.Data == null)
                return Json(new { success = false, msg = "Invalid Organisation" });

            var organisationResponse = await unitOfWork.OrganisationDetailService.Delete(id);

            if (organisationResponse != null && organisationResponse.StatusCode == HttpStatusCode.NoContent)
                return Json(new { success = true, msg = "Organisation deleted successfully" });

            if (organisationResponse != null && organisationResponse.Data != null)
            {
                if (organisationResponse.StatusCode == HttpStatusCode.BadRequest)
                {
                    var errorMessage = organisationResponse.Data.ErrorCode;
                    if (organisationResponse.Data.Errors != null)
                    {
                        errorMessage = "";
                        foreach (var error in organisationResponse.Data.Errors)
                        {
                            errorMessage = string.IsNullOrWhiteSpace(errorMessage) ? error : $"<br/>{error}";
                        }
                    }

                    return Json(new { success = false, msg = errorMessage });
                }

                return Json(new { success = false, msg = organisationResponse.Data.ErrorCode });
            }

            return Json(new { success = false, msg = "Some error occured" });
        }
    }
}

JobStationUI/Views/OrganisationDetails/Index.cshtml
@inject IUnitOfWork unitOfWork
@model List<OrganisationDetailsDto>

@{
    ViewData["Title"] = "Organisations";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="dashboard_main">

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="dashboard_main_heading">
                    <div class="heading_left">
                        <h2>Organisations</h2>
                    </div>
                    <div class="heading_right">
                        <a asp-area="" asp-controller="OrganisationDetails" asp-action="Manage" class="btn-main add-page">
                            <i class="fal fa-plus-circle"></i> Add New Organisation
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="dashboard_main_body">
        <div class="container-fluid">
            <div class="row">
                <partial name="~/Views/Shared/_ErrorMessage.cshtml" />
                <div class="col-md-12">
                    <div class="table_main">
                        <table class="table table_style table-hover" id="organisation-table">
                            <thead class="cf">
                                <tr>
                                    <th>Id</th>
                                    <th>OrganisationName</th>
                                    <th>Domain</th>
                                    <th>EstablishedYear</th>
                                    <th>Website</th>
                                    <th>Email</th>
                                    <th>Added On</th>
                                    <th class="no-sort">Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                @if (Model != null && Model.Count > 0)
                                {

                                    foreach (var organisation in Model)
                                    {
                                        <tr>

                                            <td>@organisation.Id</td>
                                            <td>@organisation.OrganisationName</td>
                                            <td>@organisation.Domain</td>
                                            <td>@organisation.EstablishedYear</td>
                                            <td>@organisation.Url</td>
                                            <td>@organisation.Email</td>

                                            <td data-sort='@organisation.CreatedOn.ToString("yyyyMMdd")'>@organisation.CreatedOn.ConvertToUserTime(unitOfWork.ClaimsService.GetTimeZone()).ToString("dd MMM, yyyy  |  hh:mm tt")</td>
                                            <td>
                                                <a class="btn icon_btn" asp-area="" asp-controller="OrganisationDetails" asp-action="Manage" asp-route-guid="@organisation.UniqueGuid"
                                                   data-bs-toggle="tooltip" data-bs-placement="top" title="Edit">
                                                    <i class="fal fa-edit"></i>
                                                </a>


                                                <a class="btn btn-sm btn-danger delete-organisation" href="#" data-href="/OrganisationDetails/Delete/@organisation.Id"
                                                   data-bs-toggle="tooltip" data-bs-placement="top" title="Delete"
                                                   data-bs-original-title="Delete" aria-label="Delete">
                                                    <i class="fal fa-trash"></i>
                                                </a>

                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>
        $(document).on('click', '.delete-organisation', function (e) {
            e.preventDefault();
            var _self = $(this);
            bootbox.confirm({
                title: "Confirm?",
                message: "Are you sure for this action?",
                centerVertical: false,
                buttons: {
                    cancel: {
                        label: '<i class="fa fa-times"></i> Cancel',
                        className: 'btn-danger'
                    },
                    confirm: {
                        label: '<i class="fa fa-check"></i> Confirm',
                        className: 'btn-success'
                    }
                },
                callback: function (result) {
                    if (result) {
                        $.ajax({
                            type: "POST",
                            url: _self.attr('data-href'),
                            success: function (data) {
                                if (data.success) {

                                    toastr.success(data.msg);

                                    setTimeout(function () {
                                        window.location.reload();
                                    }, 2000);

                                } else {
                                    $('.ajax-loader').addClass('d-none');
                                    toastr.error(data.msg);
                                }

                            },
                            error: function (req, error) {
                                toastr.error(req.responseText);
                                $('.ajax-loader').addClass('d-none');
                            },
                            beforeSend: function (data) {
                                $('.ajax-loader').removeClass('d-none');
                            }
                        });

                    }
                }
            });
        });
    </script>

}

JobStationUI/Views/OrganisationDetails/Manage.cshtml
@model OrganisationDetailsModel
@inject IUnitOfWork unitOfWork
@{
    ViewData["Title"] = "Manage Organisations";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="dashboard_main">

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-12">
                <div class="dashboard_main_heading">
                    <div class="heading_left">
                        @if (Model.Id > 0)
                        {
                            <h2>Update Organisation Details</h2>
                        }
                        else
                        {
                            <h2>Add Organisation Details</h2>
                        }
                    </div>
                    <div class="heading_right">
                        <a class="btn-main" asp-area="" asp-controller="OrganisationDetails" asp-action="Index" asp-route-projectGuid="@ViewBag.ProjectGuid">
                            <i class="fa fa-arrow-circle-left"></i> Back to Organisation Details List
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="dashboard_main_body">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-8">
                    <div class="website_settings">
                        <form name="organisationDetailsForm"
                              action="/organisationDetails/manage"
                              method="post"
                              id="organisationDetailsForm"
                              enctype="multipart/form-data">
                            @*<div asp-validation-summary="ModelOnly"></div>*@
                            <input type="hidden" id="Id" name="Id" asp-for="Id" />
                            <input type="hidden" id="UniqueGuid" asp-for="UniqueGuid" />
                            @*<input type="hidden" asp-for="ProfilePicture" />
                                <input type="hidden" asp-for="ProfilePictureWebp" />*@


                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Organisation Name*</label>
                                        <input type="text" id="OrganisationName" name="OrganisationName" placeholder="OrganisationName*" asp-for="OrganisationName" class="form-control">
                                        @*<span asp-validation-for="OrganisationName" class="text-danger"></span>*@
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Domain*</label>
                                        <input type="text" id="Domain" name="Domain" placeholder="Domain*" asp-for="Domain" class="form-control">
                                        @*<span asp-validation-for="Domain" class="text-danger"></span>*@
                                    </div>
                                </div>
                            </div>

                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Established Year*</label>
                                        <input type="text" id="EstablishedYear" name="EstablishedYear" placeholder="Established Year*" asp-for="EstablishedYear" class="form-control">
                                        @*<span asp-validation-for="EstablishedYear" class="text-danger"></span>*@
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Email*</label>
                                        <input type="text" id="Email" name="Email" placeholder="Email*" asp-for="Email" class="form-control">
                                        @*<span asp-validation-for="Email" class="text-danger"></span>*@
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Website*</label>
                                        <input type="text" id="Url" name="Url" placeholder="www.xyz.com*" asp-for="Url" class="form-control">
                                        @*<span asp-validation-for="Url" class="text-danger"></span>*@
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group text-center">
                                    <input type="submit" class="btn btn-main organisationDetailsFormBtn " id="organisationDetailsFormBtn" value="Save" />
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>  

    $(document).on('submit', '#organisationDetailsForm', function (e) {

        e.preventDefault();
        var formData = $(this).serialize();
        var buttonText = $('#organisationDetailsFormBtn').text();
        $.ajax({
            type: $(this).attr('method'),
            url: $(this).attr('action'),
            data: formData,
            success: function (data) {
                if (data.success) {
                    toastr.success(data.msg);
                    setTimeout(function () {
                        window.location.href = '/OrganisationDetails/Index'
                    }, 2000);
                }
                else {
                    $('.ajax-loader').addClass('d-none');
                    toastr.error(data.msg);
                    $('#organisationDetailsFormBtn').removeAttr('disabled');
                    $('#organisationDetailsFormBtn').text(buttonText);
                }
            },
            error: function (err, res) {

            },
            beforeSend: function () {
                $('#organisationDetailsFormBtn').attr('disabled', 'disabled').text('Please wait...');
            }
        });

    });
    </script>


}